/**
 *
 * $Id$
 */
package trafochainselection.validation;

import org.eclipse.emf.common.util.EList;

import trafochainselection.Metamodel;
import trafochainselection.Transformation;

/**
 * A sample validator interface for {@link trafochainselection.ModelTransformationRepository}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModelTransformationRepositoryValidator {
   boolean validate();

   boolean validateTransformations(EList<Transformation> value);
   boolean validateMetamodels(EList<Metamodel> value);
}
