/**
 *
 * $Id$
 */
package trafochainselection.validation;

import java.util.Map;

import trafochainselection.Metamodel;

/**
 * A sample validator interface for {@link trafochainselection.Transformation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TransformationValidator {
   boolean validate();

   boolean validateId(String value);
   boolean validateSrc(Metamodel value);
   boolean validateTarget(Metamodel value);
   boolean validateMetrics(Map<String, Double> value);

   boolean validateComplexity(int value);

   boolean validateCoverage(double value);
}
