/**
 *
 * $Id$
 */
package trafochainselection.validation;

import trafochainselection.ModelTransformationRepository;
import trafochainselection.TransformationChain;

/**
 * A sample validator interface for {@link trafochainselection.TransformationModel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TransformationModelValidator {
   boolean validate();

   boolean validateTransformationchain(TransformationChain value);
   boolean validateModelTransformationRepository(ModelTransformationRepository value);
}
